### ISSUE TITLE
problem with Heroku Link 

### ISSUE THREAD

**Issue by AnkitDubey040** [Ankit4521/movie_reccomendation_sys#4]
The issue with Heroku link and nltk is now solvable. The problem was due to the DNS error in India for Jio based Wifi an dNetworks , the issue is resolved on using other operators like BSNL and Airtel.

**Comment by Ankit4521** [comment]
Okay the issue is Solved on following the steps that you suggest , Thanks for the help

**Comment by AnkitDubey040** [comment]
![Uploading bg2.jpg…]()
